#!/bin/bash

psql -U ${POSTGRES_USER} <<-END
    CREATE USER ${DB_ANON_ROLE};
    GRANT USAGE ON SCHEMA ${DB_SCHEMA} TO ${DB_ANON_ROLE};
    GRANT SELECT ON ALL TABLES IN SCHEMA ${DB_PUBLIC} TO ${DB_ANON_ROLE};
    --GRANT INSERT ON ALL TABLES IN SCHEMA ${DB_PUBLIC} TO ${DB_ANON_ROLE};
    --GRANT UPDATE ON ALL TABLES IN SCHEMA ${DB_PUBLIC} TO ${DB_ANON_ROLE};
END