CREATE TABLE test(
    id      SERIAL          PRIMARY KEY,
    test    VARCHAR(255)    NOT NULL
);

INSERT INTO test VALUES(1, 'FOO');
INSERT INTO test VALUES(2, 'BAR');
INSERT INTO test VALUES(3, 'STUFF');
INSERT INTO test VALUES(4, 'MORE STUFF');
INSERT INTO test VALUES(5, 'EVEN MORE STUFF');
INSERT INTO test VALUES(6, 'BAR2');